sudo: required
language: python
services:
- docker
script:
- docker build -t ${IMAGE_TAG} -f ${DOCKERFILE_NAME} .
- docker run -it --rm ${IMAGE_TAG} py.test
env:
  matrix:
  - DOCKERFILE_NAME: ./Dockerfile.ubuntu16_04
    IMAGE_TAG: cloudpassage-slim-ubu1604:latest
  - DOCKERFILE_NAME: ./Dockerfile.ubuntu16_10
    IMAGE_TAG: cloudpassage-slim-ubu1610:latest
  global:
  - secure: Wao5nLzDrBRifVOxlDG8zhqn03Qh24hiGQqsKjHgmIRXgcgjOS8CxOdaLOALziIvwBcpWyj5/eVoBTSrIDlb8rZC1YCl4aNx5HHL6iMomH5iZRqmgfLFeOt9XtF4VpQcOFkezW0WsUfFt/KQ8fhbHxa2VZVoGmdV0CaruLSCU1o3cTvT05gdE3ax2IEs++y2w84I9kqh+IAzpuwYZgWWHbewM8yEjsCMn09tZSU7YjyBhB3mYGgMzgPiexZ5unK6BJbLHpfyEJBWWBlvzZQoLYkft6ieKEM3UPvMpQhfgviWyT0VifQAEDp+JYoeEzWPbsMnxvX2xQEiCNoh2WxW4wvYM3zyIYLFGEQ7tVmjF+P3gp92+DJY2QNHiJDsoPD1mzrZGzP8uagkgkjTPbOhYqhfCpsecXsgf0Hbn56cJIR8u97GCkem0D6Q2F5nrHDa+FXRXK+zxg26YMR8uUui2sAzcgP8Xh6rK8mMQfW0WIysXbNnaoBXgY8YiP6lMMWSlNW9QW4CdN0kWw11D00I2JSiiATeIOof++7IPmmVcLx4hLYn6qEY/SUNiH9WbCwI8cybAoKqfVTtqnhUGy1BQZukbSruFJ9DDxfcDHi4bnTX9uz8gG+upJQKfjmkNUHADhVIPe1CV6N0jyeyUTPiY7k++d/ivHoVM0OqEsoA2J0=
  - secure: nu6eBp8WJNVE51MwfQEeM95rgb8AW1TDfLFqAYoBUgQUspGZ3lzWJHctWKPAtlFwaZOi2/2RXUudJi/4NcOV/V8s+BHcH+mjmEoXNkSpt2yz29GCmpvvTjn7D9Tef0H0vBgdaHKqQ8T6upPKC2Z6Wz7Hw7JycTW9FR5+D40/AyNtdELtxVHdycBz7Z5jqo2YxeCREszhhwbTyTBcdsieJUTAP+9dhuGNubvdPc1uz0XLB0zWT/fEINNySMNplQBumxdKb4IKcWULSnBcG2qHHLNmx2pk+R4sRKWhGy4og7+YIsFXTQhoAAsWdhmbSysVTbiJrjw31I5ERzv5bUyQfe6wWyZwVl/sekDNQ1DY6I5KIcweJiN2VZq7bRR4rqrk1N4l9M558m8FGHhV+A3u7Kdu6mj/e8T2orGa9/z4YFD0YbRgFm3MHvrXPVhWpxpmuqepxhJcrM0ZyLV4myHBuH9iNhsbAHd6ABEGKVJM2FX1DVFeT+hzL5xg9bYxWos3pDxsoRWT/k5BxCIOrWDIviO84P6ppL3AcGkVDF3On4saediYz9cB+gHMyzZJVdLoe40suFpFBs5wqYAeePiPyYWRxwwXgNsWyF9cZrC1E6zHo9dxH8EF7zWj+dp1sELz7xzBly57M4yyk60Kb3GZ3uppd4up3ePAbSGdMzSdrG8=
