sudo: required
language: python
services:
- docker
script:
- docker build -t ${IMAGE_TAG} -f ${DOCKERFILE_NAME} .
- docker run -it --rm -e HALO_API_KEY=${HALO_API_KEY} -e HALO_API_SECRET=${HALO_API_SECRET} ${IMAGE_TAG} py.test
env:
  matrix:
  - DOCKERFILE_NAME: ./Dockerfile.ubuntu16_04
    IMAGE_TAG: cloudpassage-slim-ubu1604:latest
  - DOCKERFILE_NAME: ./Dockerfile.ubuntu16_10
    IMAGE_TAG: cloudpassage-slim-ubu1610:latest
  global:
  - secure: eJHplLGHhqiW2MeYCwPF1ajgk/O1cdeE+xnjBjwYKbBWO1xQCaspknll6E7xeacMaWdkcMtw/AQTKw0Q7XdSbg6auCkp3yZgS+kgV03ArAGiGShpvWklQeAvtFRvLtYTbpkFUTml+5Oh6nbhsWGR3Z0afieWIL/dJBZmOK8XyziTMBbMqgBeN7T4Q/CN92hhwgRwRgBZ9UXp3inuX6D+hM6QoD/Kg6rs6Jo0zWm/udj7Gp4+k3GuZw3kR303t3Ugi5EYzHjujaHesvFVod0bBoea4oW5E3TvVBbKIqYraCRfLZ66Q2BH9YZgpb4k3W77+1yCPv6ZcDr5WuX7MqsE6EXT7tFC0yFy7UVv5JXjl4jlWn5RlOOoEAxad05M9mW3+I8frSoxq1ep5f40uGuhHuGTut2s0i/2ZX1aBXv52ABBQVzbvssbs0Na0F3gHop/kkcsUmDbozosATF4TVmGATPxh5USumgSW68ry0orwZrQrLHFXzAVuM2Lb56pEu34dkfQE8ceZlSEfoJQWvobAl6JHhAzfn39alWUtE7NJFdbfrsvAM+1iQbWMPumfdZRaBvLuT+WPncSQ9q2lMMkDn0zcdZpV849jG3RffexSbtz2U6Dfw99kGa1AZjZEDOTNN5KCZlMf8L6+hISO11XTMYra6LALb/AGGPOAPM4qVI=
  - secure: b19VSejDFz6ZeWNzMQMoMd3FfJO5Xe7skRAIPcTWroE83FL02tXAIMC3HeC4Di93yULjH7rwz4eE8KDdJFWlsorzoVQVGhJ7TPVnRed8v3ZUZFBYmMhfpGu6LJ1jj41NMDYgzZB1+kratiEmK9qO2lKoix8VX5IL8AAR7cd0O+h0Y+fhVHcbmfBNIUuEr9+taRpmRAWs9uLnN2Hb0pxR4NwJuYaphANwoE/cCDjyPQ0Tk+0LkqaZned8b7RcyPE+sxgAdM1B30ZB4XUSjAgGv//9Pn00LiqexSS0pjIJEBBILn1JTrHqT8TF9B76ULDqRIMTjfBh8Eql2RVGlv4VsaYXD/DIbinpnT2S6urTf49MNp6BMDrX5M65DsP8EnS5SzDKUXIb0nLKfwmCD75TkcZRqWpCN7h35pkIFw49zBcxUlxJoREx6f0ulzxCVWADVgx36l7qxm+8IwYfgwEsUFAbXbYkOf3cVNadCQvL7muyyXlLraSI8T6RWEBv1uUkQO+VUWZAz1jes1O/BBUXmAEgZE47LAPra0Y8ewzzlhM4+EyV6+owAd9pFPO8zN8/Ybfg00uGL7owvDYKaPJm25l7CS0oIcLgKEfNqCD3LoOzzZXfOHH9DoPEcCJR2yH3GF8tZwnyOBeYCTlUU+mxqeZz8sCzU/syZGRLeOXPGsA=
