FROM ubuntu:16.04
MAINTAINER ash

RUN apt-get update && \
    apt-get install -y \
        python \
        python-pip 

RUN pip install \
    pytest \
    pytest-cov

RUN mkdir /app

COPY . /app/

WORKDIR /app/
